name: GitHub Actions SendMessage
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: WeChat Work notification by text
    uses: chf007/action-wechat-work@master
    env:
      WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
    with:
      msgtype: text
      content: hello